FROM node:22-bullseye

RUN apt-get update && apt-get install -y \
  tmux \
  telnet \
  inetutils-ping \
  net-tools \
  coreutils \
  ncurses-term \
  vim \
  default-jre \
  python3 \
  python3-pip \
  python-is-python3 \
  g++ \
  gcc \
  make \
  pkg-config \
  libx11-dev \
  libxkbfile-dev \
  libsecret-1-dev


# Set terminal color support
ENV TERM=xterm-256color
ENV CLICOLOR=1
RUN dircolors -b >> ~/.bashrc
RUN echo "alias l='ls --color=auto'" >> ~/.bashrc
RUN echo "PS1='\\[\\e[1;32m\\]\\u@\\h:\\w\\$ \\[\\e[0m\\]'" >> ~/.bashrc

# install pnpm
RUN npm install --global corepack@latest

# RUN wget -qO- https://get.pnpm.io/install.sh | ENV="$HOME/.bashrc" SHELL="$(which bash)" bash -

USER node

WORKDIR /workdir

EXPOSE 8080

CMD ["sh", "-c", "trap 'exit 0' INT TERM; while true; do sleep 1; done"]
